[package]
name = "zkvm-common"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
kona-client.workspace = true
kona-primitives.workspace = true
alloy-primitives.workspace = true
serde.workspace = true
