name: Build OP Succinct Lite Docker Images

on:
  workflow_dispatch:
  push:

jobs:
  build-proposer:
    name: Build OP Succinct Lite Proposer
    runs-on: ubuntu-latest-l
    
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            cargo-git
            cargo-registry
            target
          key: cache-proposer-${{ hashFiles('Dockerfile.proposer') }}
          restore-keys: |
            cache-proposer-

      - name: Docker meta for proposer
        id: meta-proposer
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/lite-proposer
          tags: |
            type=sha
            latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push proposer
        uses: docker/build-push-action@v6
        with:
          context: .
          file: fault-proof/Dockerfile.proposer
          push: true
          tags: ${{ steps.meta-proposer.outputs.tags }}
          labels: ${{ steps.meta-proposer.outputs.labels }}
          cache-from: |
            type=gha,scope=proposer
            type=registry,ref=ghcr.io/${{ github.repository }}/lite-proposer:cache
          cache-to: |
            type=gha,mode=max,scope=proposer
            type=registry,ref=ghcr.io/${{ github.repository }}/lite-proposer:cache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1


  build-challenger:
    name: Build OP Succinct Lite Challenger
    runs-on: ubuntu-latest-l
      
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            cargo-git
            cargo-registry
            target
          key: cache-challenger-${{ hashFiles('Dockerfile.challenger') }}
          restore-keys: |
            cache-challenger-

      - name: Docker meta for challenger
        id: meta-challenger
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/lite-challenger
          tags: |
            type=sha
            latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push challenger
        uses: docker/build-push-action@v6
        with:
          context: .
          file: fault-proof/Dockerfile.challenger
          push: true
          tags: ${{ steps.meta-challenger.outputs.tags }}
          labels: ${{ steps.meta-challenger.outputs.labels }}
          cache-from: |
            type=gha,scope=challenger
            type=registry,ref=ghcr.io/${{ github.repository }}/lite-challenger:cache
          cache-to: |
            type=gha,mode=max,scope=challenger
            type=registry,ref=ghcr.io/${{ github.repository }}/lite-challenger:cache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
